### ISSUE TITLE
About Model

### ISSUE THREAD

**Issue by jjunnii** [anticdimi/CloSe#1]
Thank you for addressing my issue.

**Comment by garvita-tiwari** [comment]
Hi,

CloSe-Net was trained to take XYZ, RGB and normals as input. During our experiments, we observe that normal information is crucial for getting more accurate segmentation, particularly around boundaries and regions with similar colors. So, incorporating normals into the input data is essential for the model. There is a way to estimate normals.

As part of our data preparation pipeline, we utilize PyTorch3D to estimate normals for our point clouds. Here's a specific snippet of code we employ:

```      
          from pytorch3d.ops import estimate_pointcloud_normals
          pc = Pointclouds(points=[verts]).to(device)
          vert_normals = estimate_pointcloud_normals(pc, neighborhood_size=50).float()[0]
```

You can use the same snippet to get normals of your pointcloud. This should work effectively, as long as the pointcloud is dense enough and not noisy.

**Comment by anticdimi** [comment]
See [prep_scan.py](https://github.com/anticdimi/CloSe/blob/main/prep_scan.py) and [docs/dataset.md](https://github.com/anticdimi/CloSe/blob/main/docs/dataset.md) for more info.
