### ISSUE TITLE
About Training Code and CloSe-T tool

### ISSUE THREAD

**Issue by jjunnii** [anticdimi/CloSe#2]
I previously inquired about model-related issues. I appreciate once again for your insightful paper, which seems highly relevant to my research. Could you please inform me when the training code and CloSe-T tool related to the paper will be made available?

**Comment by anticdimi** [comment]
Hi @jjunnii ,

Thanks for your interest! 
We aim to release the training code and CloSe-T tool by the end of this month.

I will make sure to update you here when the code is released.

**Comment by anticdimi** [comment]
Training code and CloSe-T codebase are released.
I will close this issue as resolved.

Good luck with hacking! :rofl:
