### ISSUE TITLE
Visualizer Attribute Error

### ISSUE THREAD

**Issue by sohams25** [anticdimi/CloSe#3]
I am trying to run the CloSe-T tool according to the instructions mentioned in the .md file and it throws this error:

WARNING: Using soft CircularBuffer (6144 KiB)
FEngine (64 bits) created at 0x7607d7843010 (threading is enabled)
FEngine resolved backend: OpenGL
Traceback (most recent call last):
  File "<>/interactive_tool.py", line 33, in main
    app = AppWindowO3DVisualizer(
  File "<>/interactive_tool/modules/app_visualizer.py", line 75, in __init__
    self._init_custom_actions()
  File "<>/interactive_tool/modules/app_visualizer.py", line 446, in _init_custom_actions
    self.vis.path_add_action('           Load Mesh              ', _init_mesh)
AttributeError: 'open3d.cuda.pybind.visualization.O3DVisualizer' object has no attribute 'path_add_action'
Segmentation fault (core dumped)

**Comment by bozcomlekci** [comment]
Greetings, 

We are using [our custom version of the open3d library](https://github.com/Bozcomlekci/Open3D-CloSeT). This error usually occurs when the function is not available inside the open3d installation.

Could you make sure you compiled and installed the custom version of the tool, [Open3D-CloSeT](https://github.com/Bozcomlekci/Open3D-CloSeT)?

**Comment by sohams25** [comment]
Yes, I did compile the custom version of Open3D-CloSeT, although I am facing some issues while I run `bash make.sh`. This is the exact error I'm running into:

mkdir: cannot create directory ‘build’: File exists
-- CMAKE_BUILD_TYPE is set to Release.
-- Downloading third-party dependencies to <>/Open3D-CloSeT/3rdparty_downloads
CMake Deprecation Warning at CMakeLists.txt:193 (cmake_policy):
  The OLD behavior for policy CMP0072 will be removed from a future version
  of CMake.

  The cmake-policies(7) manual explains that the OLD behaviors of all
  policies are deprecated and that a policy should be set to OLD only under
  specific short-term circumstances.  Projects should be ported to the NEW
  behavior and not rely on setting a policy to OLD.


-- Open3D 0.18.0+f97b3f0d
-- Fetching ISPC compiler
-- Building with detected instruction sets
-- Using ISPC instruction sets: avx2-i32x8
-- Using security hardening compiler flags: $<$<COMPILE_LANGUAGE:CUDA>:-Xcompiler=-fstack-protector-strong,-Wformat,-Wformat-security>;$<$<COMPILE_LANGUAGE:CXX>:-fstack-protector-strong;-Wformat;-Wformat-security>
-- Using security hardening linker flags: $<$<COMPILE_LANGUAGE:CUDA>:-Xcompiler=-Wl,-z,noexecstack,-Wl,-z,relro,-z,now,$<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,EXECUTABLE>:-pie>,$<$<CONFIG:Release>:LINKER:--strip-debug>>;$<$<COMPILE_LANGUAGE:CXX>:-Wl,-z,noexecstack;-Wl,-z,relro,-z,now;$<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,EXECUTABLE>:-pie>;$<$<CONFIG:Release>:LINKER:--strip-debug>>
-- Using security hardening compiler definitions: _FORTIFY_SOURCE=2
-- Using installed third-party library 3rdparty_threads 
-- Using installed third-party library 3rdparty_openmp 
-- Building with OpenMP
-- Using installed third-party library 3rdparty_x11 
-- Building library 3rdparty_glfw from source
CMake Deprecation Warning at 3rdparty/glfw/CMakeLists.txt:3 (cmake_minimum_required):
  Compatibility with CMake < 3.5 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.


-- Could NOT find Vulkan (missing: VULKAN_LIBRARY VULKAN_INCLUDE_DIR) 
-- Using X11 for window creation
-- Building third-party library JPEG from source
-- NASM assembler not found - libjpeg-turbo performance may suffer
-- libturbojpeg: WITH_CRT_DLL=OFF
-- pybind11 v2.11.1 
-- Using prebuilt third-party library Filament
-- GLIBC version 2.35-0 found: Using Open3D Filament binary.
-- Filament is located at <>/Open3D-CloSeT/build/filament/src/ext_filament
-- Searching in for libc++ and libc++abi
-- Searching /usr/lib/llvm-15/lib for libc++ and libc++abi
-- Searching /usr/lib/llvm-14/lib for libc++ and libc++abi
-- Searching /usr/lib/llvm-13/lib for libc++ and libc++abi
-- Searching /usr/lib/llvm-12/lib for libc++ and libc++abi
-- Searching /usr/lib/llvm-11/lib for libc++ and libc++abi
-- Searching /usr/lib/llvm-10/lib for libc++ and libc++abi
-- Searching /usr/lib/llvm-9/lib for libc++ and libc++abi
-- Searching /usr/lib/llvm-8/lib for libc++ and libc++abi
-- Searching /usr/lib/llvm-7/lib for libc++ and libc++abi
CMake Error at 3rdparty/find_dependencies.cmake:1367 (message):
  Cannot find matching libc++ and libc++abi libraries with version >=7.
Call Stack (most recent call first):
  CMakeLists.txt:503 (include)


-- Configuring incomplete, errors occurred!
make: *** No targets specified and no makefile found.  Stop.
make: *** No rule to make target 'install-pip-package'.  Stop

**Comment by bozcomlekci** [comment]
Compilation and installation fails in your environment because you are missing the following:

```Cannot find matching libc++ and libc++abi libraries with version >=7.```

These are commonly used libraries, could you install them with sudo and try again?

**Comment by sohams25** [comment]
Hey,
So I reinstalled the libc6 with the aptitude package manager: `sudo aptitude reinstall libc6` and it worked.
Thank you!
