### ISSUE TITLE
Can the segmented mesh be exported?

### ISSUE THREAD

**Issue by MontaEllis** [anticdimi/CloSe#5]
Nice work! I wonder if we can export segmented cloth or shoes in mesh?

**Comment by anticdimi** [comment]
Hi @MontaEllis,

If you run demo.py with an arbitrary (preprocessed) mesh, the segmented vertices will automatically be saved.
You can extract the points for any class simply by doing something like this: 
```
interesting_verts = vertices[labels == YOUR_LABEL_OF_INTEREST]
```
Assuming `vertices` and `labels` are vertices and predicted segmentation labels tensors, respectively.

The list of per-clothing-class label IDs can be found [here](https://github.com/anticdimi/CloSe/blob/main/docs/dataset.md).

PS. Please reopen the issue if needed 😊

Best,
Dimitrije
