### ISSUE TITLE
Could I use the CloSeT to load the CloSe Di without segmentation labels?

### ISSUE THREAD

**Issue by LrobotD** [anticdimi/CloSe#8]
Thanks for your wonderful work! I can load the ".npz" file in CloSe Di dataset through CloSeT, visualize the 3D "points" reconstruction with "labels" information from ".npz". I want to visualize the original 3D reconstruction with "colors" textured reconstruction before labeling, what could I do?

**Comment by bozcomlekci** [comment]
Hi, thanks for your interest,

If you only want to visualize the original textured mesh from the ".npz" file, you can play with the "Texture blend factor" under "Labelling Controls". "Texture blend factor" being 1.0 means that the loaded ".npz" mesh completely uses the texture colors without blending label colors.

I hope that it answers your question.
![Screenshot from 2024-11-19 13-54-31](https://github.com/user-attachments/assets/0c2e7034-c2cd-4a33-ab19-a6a89ae889db)

**Comment by LrobotD** [comment]
Thanks for your answer,  I will try it.
