### ISSUE TITLE
How to extract the dataset and code from the repo

### ISSUE THREAD

**Issue by team3cevi** [anticdimi/CloSe#9]
Actually we needed to work on the given sample data and code can u explain in which environment with what setup it has to be run

**Comment by anticdimi** [comment]
Hi @team3cevi ,

For environment setup, follow the instructions provided [here](https://github.com/anticdimi/CloSe?tab=readme-ov-file#environment-setup).

I has been tested on a few machines, so a simple conda install from the .yaml file should work.
Please reopen if you have trouble.

**Comment by team3cevi** [comment]
hello could you please specify the version and suitable website or the app
to be installed like im unable to do few steps due to unsupported types
also a few tips as the dataset provided had been showing up as some
different language , thank you for your response
